name: meal_recipe_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  image_picker: ^0.8.5+3
  cached_network_image: ^3.2.1
  path_provider: ^2.0.11
  shared_preferences: ^2.0.16
  json_annotation: ^4.8.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
